
import java.awt.Image;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Germán
 */
public class PantallaPrin extends javax.swing.JFrame {

    private final Random random = new Random();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrin.class.getName());

    private final String[] nombresIconos = {"gato.png", "miguelTorres.png", "quevedo.png", "uwu.png"};

    public PantallaPrin() {
        initComponents();
        setLocationRelativeTo(null);
        configurarComponentes();
    }

    private void configurarComponentes() {
        cargarIconoVentana(nombresIconos[0]); // Empezar con el gato
    }

    private void cargarIconoVentana(String nombreIcono) {
        String pathRecurso = "/Memes/" + nombreIcono;

        // 2. Obtener la URL del recurso
        URL imgUrl = getClass().getResource(pathRecurso);

        // 3. Validar si se encontró el recurso
        if (imgUrl != null) {

            // 4. Crear un ImageIcon (este es el "puente")
            ImageIcon icono = new ImageIcon(imgUrl);

            Image imagen = icono.getImage();

            setIconImage(imagen);

        } else {
            System.err.println("Error: No se encontró el recurso: " + pathRecurso);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCambiar.setText("Cambiar Icono");
        jButtonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButtonCambiar)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jButtonCambiar)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarActionPerformed

        String iconoAleatorio = nombresIconos[random.nextInt(nombresIconos.length)];

        // 2. Llamar a nuestro método personalizado
        cargarIconoVentana(iconoAleatorio);
    }//GEN-LAST:event_jButtonCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiar;
    // End of variables declaration//GEN-END:variables
}
