
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Germán
 */
public class TareasLocasPantalla extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TareasLocasPantalla.class.getName());

    
    // Modelo de la tabla principal
    DefaultTableModel modelotabla;
    /**
     * Creates new form TareasLocasPantalla
     */
    public TareasLocasPantalla() {
        initComponents();
        setLocationRelativeTo(null);
        configurarTabla();
    }

    private void configurarTabla() {
        // Obtenemos el modelo de la tabla que NetBeans creó
        modelotabla = (DefaultTableModel) jTableTareas.getModel();

        // Limpiamos columnas por si NetBeans agregó alguna por defecto
        modelotabla.setColumnCount(0);

        // Añadimos las columnas que queremos (Tarea y Prioridad)
        modelotabla.addColumn("Tarea");
        modelotabla.addColumn("Prioridad");

        // Añadimos las filas con las tareas locas
        modelotabla.addRow(new Object[]{"Comprar 1kg de nubes", "Baja"});
        modelotabla.addRow(new Object[]{"Enseñar a la IA a soñar", "Alta"});
        modelotabla.addRow(new Object[]{"Calcular PI con un ábaco", "Media"});
        modelotabla.addRow(new Object[]{"Secuestrar al Gato de Schrödinger", "Alta"});
        modelotabla.addRow(new Object[]{"Lavar el coche (en la lavadora)", "Baja"});
        modelotabla.addRow(new Object[]{"Optimizar el código de la Matrix", "Alta"});
        modelotabla.addRow(new Object[]{"Debatir filosofía con una tostadora", "Media"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTareas = new javax.swing.JTable();
        jButtonFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarea", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTareas);

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFiltrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFiltrar)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
               // 1. Crear un nuevo modelo de tabla para el popup
        DefaultTableModel modelFiltrado = new DefaultTableModel();
        modelFiltrado.addColumn("Tarea");
        modelFiltrado.addColumn("Prioridad");

        // 2. Recorrer la tabla principal (modelotabla)
        int numFilas = modelotabla.getRowCount();
        for (int i = 0; i < numFilas; i++) {
            
            // Obtenemos los datos de la fila actual
            String tarea = (String) modelotabla.getValueAt(i, 0); // Columna 0 = Tarea
            String prioridad = (String) modelotabla.getValueAt(i, 1); // Columna 1 = Prioridad

            // 3. Aplicamos el filtro
            if (prioridad.equals("Alta")) {
                // Si cumple, la añadimos al nuevo modelo
                modelFiltrado.addRow(new Object[]{tarea, prioridad});
            }
        }

        // 4. Comprobar si encontramos resultados
        if (modelFiltrado.getRowCount() == 0) {
            // Si no hay tareas 'Alta', mostrar mensaje simple
            JOptionPane.showMessageDialog(
                    this,
                    "¡Felicidades! No hay tareas 'locas' de prioridad alta.",
                    "Filtro Vacío",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            // 5. Si SÍ hay resultados, creamos la JTable temporal
            JTable tablaPopup = new JTable(modelFiltrado);

            // 6. Creamos un JScrollPane para la tabla del popup         
            JScrollPane scrollPopup = new JScrollPane(tablaPopup);
            
            // 7. Mostramos el JScrollPane (que contiene la JTable) en el JOptionPane
            JOptionPane.showMessageDialog(
                    this, // Padre
                    scrollPopup, // El componente a mostrar (¡no un string!)
                    "Tareas de Prioridad Alta", // Título del popup
                    JOptionPane.INFORMATION_MESSAGE // Icono
            );
        }
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TareasLocasPantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTareas;
    // End of variables declaration//GEN-END:variables
}
