
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class PantallaSecundaria extends javax.swing.JDialog {
    private PantallaPrincipal pantallaPrincipal;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaSecundaria.class.getName());

    /**
     * Creates new form PantallaSecundaria
     */
    public PantallaSecundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
        pantallaPrincipal=(PantallaPrincipal)parent;
        
        initComponents();
        actualizarImagen();
        jButtonCalcular.setEnabled(false);
         ValidationGroup group= validationPanel1.getValidationGroup(); 
       group.add(jTextFieldPrimerNumero, StringValidators.REQUIRE_NON_EMPTY_STRING); 
        group.add(jTextFieldPrimerNumero, StringValidators.REQUIRE_VALID_INTEGER);      
         
         
       validationPanel1.addChangeListener(new ChangeListener() { 
    @Override 
    public void stateChanged(ChangeEvent e) { 
        if (validationPanel1.getProblem() == null) 
            jButtonCalcular.setEnabled(true); 
        else 
            jButtonCalcular.setEnabled(false); 
    } 

 


});
   }
private void actualizarImagen(){
String operacion = (String)jComboBoxTipoOperacion.getSelectedItem();
        switch (operacion) {
            case "Suma":
                jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/sumar.png")));
                break;
            case "Resta":
                jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/restar.png")));
                break;
            case "Multiplicación":
                jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/multiplicar.png")));
                break;
            case "División":
                jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dividir.png")));
                break;
            default:
                jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/potencia.jpg")));
                break;
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jComboBoxTipoOperacion = new javax.swing.JComboBox<>();
        jTextFieldPrimerNumero = new javax.swing.JTextField();
        jSpinnerSegundoNumero = new javax.swing.JSpinner();
        jButtonCalcular = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.jLabel3.text")); // NOI18N

        jLabelImagen.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.jLabelImagen.text")); // NOI18N
        jLabelImagen.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabelImagenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jComboBoxTipoOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División", "Potencia" }));
        jComboBoxTipoOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoOperacionActionPerformed(evt);
            }
        });

        jTextFieldPrimerNumero.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.Primer numero.text")); // NOI18N
        jTextFieldPrimerNumero.setName("Primer numero"); // NOI18N

        jSpinnerSegundoNumero.setModel(new javax.swing.SpinnerNumberModel());

        jButtonCalcular.setText(org.openide.util.NbBundle.getMessage(PantallaSecundaria.class, "PantallaSecundaria.jButtonCalcular.text")); // NOI18N
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonCalcular)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButtonCalcular)
                .addContainerGap(94, Short.MAX_VALUE))
            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
     double resultado=0;
        String nombreOperacion = (String)jComboBoxTipoOperacion.getSelectedItem();
     int primerNumero = Integer.parseInt(jTextFieldPrimerNumero.getText());
     int segundoNumero = (int)jSpinnerSegundoNumero.getValue();
    if(nombreOperacion.equals("Suma")){
    resultado = primerNumero+segundoNumero;
}else if(nombreOperacion.equals("Resta")){
     resultado = primerNumero-segundoNumero;
}else if(nombreOperacion.equals("Multiplicación")){
    resultado = primerNumero*segundoNumero;
}else if(nombreOperacion.equals("División")){
    if(segundoNumero==0){
    JOptionPane.showMessageDialog(this, "El segundo numero no puede ser cero si quieres dividir", "Advertencia", JOptionPane.ERROR_MESSAGE); 
    return;
    }else{
    resultado = primerNumero/segundoNumero;
    }
}else{
     resultado = Math.pow(primerNumero, segundoNumero);
}
     
    Calculos calculo = new Calculos(nombreOperacion, primerNumero, segundoNumero, resultado);
    pantallaPrincipal.aniadirDatos(calculo);
    this.dispose();
    
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jLabelImagenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabelImagenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelImagenAncestorAdded

    private void jComboBoxTipoOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoOperacionActionPerformed
        actualizarImagen();
    }//GEN-LAST:event_jComboBoxTipoOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComboBoxTipoOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerSegundoNumero;
    private javax.swing.JTextField jTextFieldPrimerNumero;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
