import java.util.ArrayList; // <--- AÑADIR ESTA
import java.util.Comparator; // <--- ASEGURARSE DE TENER ESTA
import java.util.List;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class PantallaPrincipal extends javax.swing.JFrame {
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
     private TableRowSorter<DefaultTableModel> sorter;
    public PantallaPrincipal() {
        initComponents();
        inicializarTabla();
        java.awt.Image icono = new ImageIcon(getClass().getResource("/imgs/calculadora.png")).getImage();
        this.setIconImage(icono);
        DefaultComboBoxModel dcm =new DefaultComboBoxModel();
        for(LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels())
            dcm.addElement(lfi.getName());
        jComboBox1.setModel(dcm);

    }
  private void inicializarTabla(){
  DefaultTableModel dtm = new DefaultTableModel();
  dtm.setColumnIdentifiers(new String[]{"Nombre Operacion", "1º numero", "2º numero", "Resultado"});   
  jTableOperaciones.setModel(dtm);
  sorter = new TableRowSorter<>(dtm);
    jTableOperaciones.setRowSorter(sorter);

    // 4. (CLAVE) DECIRLE CÓMO ORDENAR LA COLUMNA "RESULTADO" (índice 3)
    // Forzamos a que compare los Strings como si fueran números (Doubles)
    sorter.setComparator(3, new Comparator<String>() {
        @Override
        public int compare(String s1, String s2) {
            try {
                // Intenta convertir el texto a número para comparar
                Double d1 = Double.parseDouble(s1);
                Double d2 = Double.parseDouble(s2);
                return d1.compareTo(d2); // Comparación numérica
            } catch (NumberFormatException e) {
                // Si algo falla (ej. texto vacío), usa la comparación normal
                return s1.compareTo(s2);
            }
        }
    });

    // 5. ESTABLECER EL ORDEN POR DEFECTO: Col 3 (Resultado), Descendente
    List<RowSorter.SortKey> sortKeys = new ArrayList<>();
    sortKeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING));
    
    sorter.setSortKeys(sortKeys);
  }
  
  public void aniadirDatos(Calculos calculo){
  DefaultTableModel dtm = (DefaultTableModel)jTableOperaciones.getModel(); 
  dtm.addRow(calculo.toArrayString()); 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOperaciones = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminarOperacion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNuevaOperacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOperaciones);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jLabel1.text")); // NOI18N

        jButtonEliminarOperacion.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jButtonEliminarOperacion.text")); // NOI18N
        jButtonEliminarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarOperacionActionPerformed(evt);
            }
        });

        jMenu1.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenu1.text")); // NOI18N

        jMenuItemNuevaOperacion.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenuItemNuevaOperacion.text")); // NOI18N
        jMenuItemNuevaOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaOperacionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNuevaOperacion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarOperacion))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButtonEliminarOperacion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevaOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaOperacionActionPerformed
        PantallaSecundaria  irPantallaSecundaria = new PantallaSecundaria  (this, true); 
        irPantallaSecundaria.setVisible (true);
    }//GEN-LAST:event_jMenuItemNuevaOperacionActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      try{
    LookAndFeelInfo lookAndFeel = UIManager . getInstalledLookAndFeels ( ) [ jComboBox1.getSelectedIndex()];
    UIManager. setLookAndFeel(lookAndFeel. getClassName () ) ;
    SwingUtilities. updateComponentTreeUI(this) ;
      }
    catch (Throwable e){
    }              

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonEliminarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarOperacionActionPerformed
        // 1. OBTENER EL MODELO DE LA TABLA
    DefaultTableModel dtm = (DefaultTableModel) jTableOperaciones.getModel();

    // 2. PEDIR DATOS (Pop-up de búsqueda)
    // Para simplificar, buscaremos por "Nombre de la Operación".
    String nombreBuscado = JOptionPane.showInputDialog(this,"Introduce el Nombre de la Operación a eliminar:", "Buscar Operación",JOptionPane.QUESTION_MESSAGE);
           


    // Si el usuario presiona "Cancelar" o no escribe nada, salimos.
    if (nombreBuscado == null) {
        return; // No hacer nada
    }

    // --- Búsqueda de la Fila ---
    int filaEncontrada = -1; // -1 significa que no la hemos encontrado
    String nombreOperacion = "";
    String resultadoOperacion = ""; // Guardamos los datos para los mensajes

    // Recorremos toda la tabla
    for (int i = 0; i < dtm.getRowCount(); i++) {
        // Obtenemos el valor de la columna 0 (Nombre Operacion)
        String nombreEnTabla = (String) dtm.getValueAt(i, 0);
        
        // Comparamos si es el que buscamos (ignorando mayús/minús)
        if (nombreEnTabla.equalsIgnoreCase(nombreBuscado)) {
            filaEncontrada = i; // ¡La encontramos! Guardamos su índice
            
            // Guardamos los datos de esa fila para usarlos en los mensajes
            nombreOperacion = (String) dtm.getValueAt(i, 0);
            resultadoOperacion = (String) dtm.getValueAt(i, 3); // Columna 3 es "Resultado"
            
            break; // Dejamos de buscar
        }
    }

    // --- Verificación y Confirmación ---

    if (filaEncontrada == -1) {
        // CASO "NO ENCONTRADO"
     JOptionPane.showMessageDialog(this,
                "No se encontró ninguna operación con el nombre '" + nombreBuscado + "'.",
                "Error de Búsqueda",
              JOptionPane.WARNING_MESSAGE);
    } else {
        // CASO "ENCONTRADO"
        // 3. POP-UP DE CONFIRMACIÓN (SÍ/NO)
        int confirmacion =JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres eliminar la operación '" + nombreOperacion + "'?",
                "Confirmar Eliminación",
             JOptionPane.YES_NO_OPTION,
               JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // ■ Si confirma SÍ →
           JOptionPane.showMessageDialog(this,
                    "De acuerdo, eliminamos la operación " + nombreOperacion + " con resultado " + resultadoOperacion,
                    "Operación Eliminada",
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Finalmente, eliminamos la fila del modelo
            dtm.removeRow(filaEncontrada);
            
        } else {
            // ■ Si pulsa NO →
         JOptionPane.showMessageDialog(this,
                    "Sabía que no te querías perder la operación " + nombreOperacion + " con resultado " + resultadoOperacion,
                    "Operación Conservada",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonEliminarOperacionActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarOperacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemNuevaOperacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOperaciones;
    // End of variables declaration//GEN-END:variables
}
