
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Germán
 */
public class pantPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pantPrincipal.class.getName());

    /**
     * Creates new form pantPrincipal
     */
    public pantPrincipal() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("German Decision Superheroe");

        jButtonMision.setText("Mision Peligrosa");
        jButtonMision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButtonMision, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButtonMision, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisionActionPerformed
        // 1. Mostrar el ConfirmDialog con opciones SÍ/NO
        int respuesta = JOptionPane.showConfirmDialog(
                this, // Padre
                "¿Aceptas la misión peligrosa?", // Mensaje
                "¡Misión URGENTE!", // Título
                JOptionPane.YES_NO_OPTION, // Tipo de botones
                JOptionPane.WARNING_MESSAGE // Icono (de advertencia)
        );

        // 2. Procesar la respuesta
        if (respuesta == JOptionPane.YES_OPTION) {
            // SÍ
            JOptionPane.showMessageDialog(
                    this,
                    "¡Misión aceptada! 🚀",
                    "¡Héroe en Camino!",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else if (respuesta == JOptionPane.NO_OPTION) {
            // NO
            JOptionPane.showMessageDialog(
                    this,
                    "Misión rechazada. 😴",
                    "Héroe Rechazo",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            // El usuario cerró el diálogo (CLOSED_OPTION)
            JOptionPane.showMessageDialog(
                    this,
                    "El héroe se lo está pensando...",
                    "Héroe Indeciso",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonMisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pantPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMision;
    // End of variables declaration//GEN-END:variables
}
