
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Germán
 */
public class pantPrinPopMulti extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pantPrinPopMulti.class.getName());

    /**
     * Creates new form pantPrinPopMulti
     */
    public pantPrinPopMulti() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Popup Multifuncion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // 1. Elegir Clase
        Object[] clases = {"Guerrero ⚔️", "Mago 🔮", "Arquero 🏹"};
        String clase = (String) JOptionPane.showInputDialog(
                this,
                "Paso 1: Elige tu clase",
                "Creador de Personajes",
                JOptionPane.QUESTION_MESSAGE,
                null,
                clases,
                clases[0]
        );

        if (clase == null) {
            return; // Canceló
        }
        // 2. Elegir Nombre
        String nombre = JOptionPane.showInputDialog(
                this,
                "Paso 2: ¿Cómo se llamará tu " + clase.split(" ")[0] + "?", // "Guerrero", "Mago", etc.
                "Nombre del Héroe",
                JOptionPane.INFORMATION_MESSAGE
        );

        if (nombre == null || nombre.trim().isEmpty()) {
            return; // Canceló
        }
        nombre = nombre.trim();

        // 3. Confirmar Extra
        int pocion = JOptionPane.showConfirmDialog(
                this,
                "Paso 3: ¿Añadir una Poción de Vida inicial? 🧪",
                "Extras",
                JOptionPane.YES_NO_OPTION
        );

        String extra = (pocion == JOptionPane.YES_OPTION) ? "con Poción de Vida" : "sin extras";

        // 4. Resumen
        String resumen = String.format(
                "¡Personaje Creado! \n\n"
                + " - Nombre: %s\n"
                + " - Clase: %s\n"
                + " - Extra: %s\n",
                nombre, clase, extra
        );
        JOptionPane.showMessageDialog(this, resumen);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pantPrinPopMulti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
